### ISSUE TITLE
Statistics after Import

### ISSUE THREAD

**Issue by seanap** [johanohly/AirTrail#10]
### The bug

I noticed that after doing an app in the air import the top row of numerical statistics did not update.  The charts were updated and did show the correct data.  Once I shut the docker down and restarted it all the statistics were there.

### Operating System that is running AirTrail

Windows

### AirTrail Version

latest

### Reproduction steps

1. app in the air import
2. go to statistics
3. restart docker
...

**Comment by johanohly** [comment]
I have noticed that statistics after adding flights do not update and require a refresh of the page (sometimes?). I'll have to investigate this further.

**Comment by Maxklos** [comment]
Can confirm, Statistic showed still 0 flights after successful import. After refreshing the site it worked.

**Comment by johanohly** [comment]
Fixed in v0.1.1
