### ISSUE TITLE
First Day of the Week Error

### ISSUE THREAD

**Issue by wilcochris** [johanohly/AirTrail#136]
### The bug

When selecting the calendar, the first day of the week is a Tuesday (not a Sunday or Monday as is usual).

### Operating System that is running AirTrail

Windows

### AirTrail Version

v1.0.0

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

1. Go to add a flight
2. Select the calendar icon
3. Calendar pops up with Tuesday as the first day of the week
...

### Additional information

This has happened since the TimeZone rework
![Screenshot 2024-11-13 at 14-47-09 AirTrail](https://github.com/user-attachments/assets/c371e049-8194-48a6-81d1-858702716107)

**Comment by johanohly** [comment]
Thank you for reporting this!
The first weekday will follow your browser preference in the next release.

**Comment by johanohly** [comment]
Released in v1.1.1
