### ISSUE TITLE
Cannot add flights Manually

### ISSUE THREAD

**Issue by sojufx** [johanohly/AirTrail#15]
### The bug

When tries to add flights manually the ui is stuck at a point cannot scroll or do anything. Tried safari and chrome.
<img width="1461" alt="Screenshot 2024-09-12 at 1 27 37 PM" src="https://github.com/user-attachments/assets/777bb679-0191-41b4-b81d-51dc43ab759b">
 

### Operating System that is running AirTrail

Mac OS

### AirTrail Version

v.1.0

### Reproduction steps

1. Try to add flights Manually.
2.
3.
...

**Comment by johanohly** [comment]
Thank you for reporting this issue! It has already been fixed and will be available in the next release.

**Comment by sojufx** [comment]
@johanohly That's great. Thank you very much.

**Comment by johanohly** [comment]
> @johanohly That's great. Thank you very much.

No worries, it does make the app kind of unusable on smaller screens 😐

**Comment by johanohly** [comment]
Fixed in v0.1.0

**Comment by sojufx** [comment]
@johanohly Thank you.
