### ISSUE TITLE
arm64 not present on Dockerhub

### ISSUE THREAD

**Issue by gmemstr** [johanohly/AirTrail#16]
### The bug

The arm64 images are not available on the Dockerhub, despite being build in the GHA.

### Operating System that is running AirTrail

N/A

### AirTrail Version

v0.0.3

### Reproduction steps

https://hub.docker.com/r/johly/airtrail/tags

**Comment by johanohly** [comment]
I had to hotfix a broken feature in v0.0.3 and only built it locally on amd64, sorry about that. The next release (and hopefully everyone after that) will include ARM64 builds.

**Comment by johanohly** [comment]
Fixed in v0.1.0
