### ISSUE TITLE
Smaller airport missing from drop down

### ISSUE THREAD

**Issue by atribe** [johanohly/AirTrail#30]
### The bug

https://en.wikipedia.org/wiki/Williston_Basin_International_Airport This airport isn't in the drop down list. Tried to search by name and to search by abbreviations [IATA](https://en.wikipedia.org/wiki/IATA_airport_code): XWA, [ICAO](https://en.wikipedia.org/wiki/ICAO_airport_code): KXWA, [FAA](https://en.wikipedia.org/wiki/Federal_Aviation_Administration) [LID](https://en.wikipedia.org/wiki/Location_identifier): XWA

### Operating System that is running AirTrail

Linux

### AirTrail Version

v0.1.1

### Reproduction steps

1. add new flight
2. set Denver as from
3. enter xwa as to

result is not found

**Comment by johanohly** [comment]
This should definitely be in the database. I found a small oversight in my parsing script which led to several larger airports not being included. 
This will be fixed in the next release!

**Comment by johanohly** [comment]
Fixed in v0.1.2
