### ISSUE TITLE
Searching for OMA fails to return Eppley Airfiled

### ISSUE THREAD

**Issue by atribe** [johanohly/AirTrail#35]
### The bug

In the to and from fields if I search OMA it doesn't find Eppley Airfield. But if I search for Epply it works. The abbreviation for Eppley Airfield is OMA, which shows in the drop down.

### Operating System that is running AirTrail

Ubuntu

### AirTrail Version

v0.1.2

### Reproduction steps

1. create a new flight
2. search for OMA
nothing is found

**Comment by johanohly** [comment]
Good catch! 
There was a bug in the search function not prioritizing exact matches like IATA code "OMA" so the result got cut off by the limit of results shown. 
Thank you for reporting this bug, it will be fixed in the next release.

**Comment by johanohly** [comment]
Fixed in v0.2.0
