### ISSUE TITLE
Inconsistent airport count in statistics

### ISSUE THREAD

**Issue by rspencer01** [johanohly/AirTrail#37]
### The bug

With four flights between three airports (`LHR`, `CPT` and `FAHT`) the statistics page shows 4 airports in the breakdown by continent.

### Operating System that is running AirTrail

Ubuntu Linux

### AirTrail Version

johly/airtrail:latest 31a1504296fd

### Reproduction steps

1. Added four flights: return `LHR` to `CPT` and return `CPT` to `FAHT`
2. Checked statistics page

### Additional information

FAHT is [Hoedspruit airport](https://en.wikipedia.org/wiki/Air_Force_Base_Hoedspruit) which is both a civilian airport (FAHT) and an airforce base (FAHS).

![image](https://github.com/user-attachments/assets/8960ab61-dc11-4cee-853b-bc4d80cfb0ff)

**Comment by johanohly** [comment]
Oh I see how that chart can be misleading. It shows, out of all flights, what the most common continents are - regardless of airport (it does use the airport to determine the continent, but that is besides the point).
If I understand correctly, you thought it shows which unique airports visited are in which continents.

**Comment by rspencer01** [comment]
Yes, given its relation to the box above I thought it was a breakdown of every airport flown to

**Comment by johanohly** [comment]
I had not considered this, as the other pie charts are clearly unrelated to their counterparts. Not sure if switching the order of the pie charts would be helpful or more confusing?
