### ISSUE TITLE
It is not possible to add no longer active airlines

### ISSUE THREAD

**Issue by DKeppi** [johanohly/AirTrail#40]
### The bug

Unfortunately it is not possible to add no longer active airlines, such as AirBerlin (AB) and Niki(HG) to my flights

### Operating System that is running AirTrail

Linux

### AirTrail Version

v1.0.2

### Reproduction steps

Try to add the airlines AirBerlin (AB) and Niki(HG) to a flight

**Comment by johanohly** [comment]
This is a known limitation, as AirTrail stores airlines by ICAO code. So if I were to use a more "complete" list of airlines, conflicts would occur, as retired ICAO codes *may* be reused.

**Comment by DKeppi** [comment]
Thats sad, but i understand the problem! 
Anyway, the flights im talking about are from 2014/2014...doesnt matter ;)
