### ISSUE TITLE
Provide a way to customise the container name of the database

### ISSUE THREAD

**Issue by savvasdalkitsis** [johanohly/AirTrail#6]
### The bug

In my setup, I have a preexisting postgres database I want to use but the container is deployed under a different name than "db" which this app expects.

It would be nice to be able to specify the name of the db container and not have it hardcoded

### Operating System that is running AirTrail

Ubuntu

### AirTrail Version

latest

### Reproduction steps

N/A

**Comment by johanohly** [comment]
If you run the app manually or without the provided database, the only thing you have to change is the `DB_URL` environment variable. 

The other `DB_`  variables are only used by the preconfigured postgres container, which I definitely have to document though.
