### ISSUE TITLE
[Bug Report] Incorrect Date/Time Behaviors

### ISSUE THREAD

**Issue by Walmarpole** [johanohly/AirTrail#80]
### The bug

Flights that cover multiple dates fail to display this correctly in the "List Flights" interface and the same interface displays full date and time for mid-morning flights only.

For multi-day flights, no full date to demonstrate this is displayed and editing these flights show that stored data sets arrivals automatically to departure date in testing.

### Operating System that is running AirTrail

Windows 11

### AirTrail Version

v1.3.2

#### Test Case 1 ##Multi-date Erroneous Correction
1. Add flight with following data: Any airport. Oct 12, 23:10 departure and Oct 13, 5:10 arrival. 
2. Leave all other fields blank and add flight. 
3. Enter "List Flights" to view issue and edit associated flight to demonstrate date being set.

#### Test Case 2 ##Full Date Time in Mid-Morning Only
1. Add flight with following data: Any airport. Oct 12, 5:55 depature and Oct 12, 7:15 arrival.
2. Leave all other fields blank and add flight
3. Enter "List Flights" to view issue

**Comment by johanohly** [comment]
That is a very good catch, not sure how that hasn't come up yet in my testing. I am planning a complete overhaul of the time-zone conversion logic, as the current system is convoluted and does not even take into account DST at all. I will investigate your example further at that time as well. 

Thank you for reporting this!
